import * as React from 'react';
import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry';
import Head from "next/head";
import './global.css'
import {SessionProvider} from "next-auth/react";
import {NextAuthProvider} from "@/app/providers";

export const metadata = {
  title: 'Thein',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
      <NextAuthProvider>

      <ThemeRegistry>{children}</ThemeRegistry>
      </NextAuthProvider>
      </body>
    </html>
  );
}
